/* Auto-generated by genmsg_cpp for file /home/dabiri/ros/setpt_source/msg/SetptResult.msg */
#ifndef SETPT_SOURCE_MESSAGE_SETPTRESULT_H
#define SETPT_SOURCE_MESSAGE_SETPTRESULT_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace setpt_source
{
template <class ContainerAllocator>
struct SetptResult_ : public ros::Message
{
  typedef SetptResult_<ContainerAllocator> Type;

  SetptResult_()
  : position(0.0)
  {
  }

  SetptResult_(const ContainerAllocator& _alloc)
  : position(0.0)
  {
  }

  typedef float _position_type;
  float position;


private:
  static const char* __s_getDataType_() { return "setpt_source/SetptResult"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "e4e11b3af29ed247b2bd150d3f4540f9"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
float32 position\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, position);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, position);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(position);
    return size;
  }

  typedef boost::shared_ptr< ::setpt_source::SetptResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::setpt_source::SetptResult_<ContainerAllocator>  const> ConstPtr;
}; // struct SetptResult
typedef  ::setpt_source::SetptResult_<std::allocator<void> > SetptResult;

typedef boost::shared_ptr< ::setpt_source::SetptResult> SetptResultPtr;
typedef boost::shared_ptr< ::setpt_source::SetptResult const> SetptResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::setpt_source::SetptResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::setpt_source::SetptResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace setpt_source

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::setpt_source::SetptResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4e11b3af29ed247b2bd150d3f4540f9";
  }

  static const char* value(const  ::setpt_source::SetptResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe4e11b3af29ed247ULL;
  static const uint64_t static_value2 = 0xb2bd150d3f4540f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::setpt_source::SetptResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "setpt_source/SetptResult";
  }

  static const char* value(const  ::setpt_source::SetptResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::setpt_source::SetptResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
float32 position\n\
\n\
";
  }

  static const char* value(const  ::setpt_source::SetptResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::setpt_source::SetptResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::setpt_source::SetptResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetptResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::setpt_source::SetptResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::setpt_source::SetptResult_<ContainerAllocator> & v) 
  {
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SETPT_SOURCE_MESSAGE_SETPTRESULT_H

