# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sled_control.ui'
#
# Created: Sat Oct  8 18:34:47 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SledControl_MainWindow(object):
    def setupUi(self, SledControl_MainWindow):
        SledControl_MainWindow.setObjectName("SledControl_MainWindow")
        SledControl_MainWindow.resize(668, 629)
        self.centralwidget = QtGui.QWidget(SledControl_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.runTab = QtGui.QWidget()
        self.runTab.setObjectName("runTab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.runTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtGui.QSplitter(self.runTab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_7 = QtGui.QWidget(self.splitter)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.runTreeWidget = QtGui.QTreeWidget(self.widget_7)
        self.runTreeWidget.setObjectName("runTreeWidget")
        self.runTreeWidget.headerItem().setText(0, "1")
        self.verticalLayout_5.addWidget(self.runTreeWidget)
        self.widget_4 = QtGui.QWidget(self.splitter)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.runInformationLabel = QtGui.QLabel(self.widget_4)
        self.runInformationLabel.setObjectName("runInformationLabel")
        self.verticalLayout_3.addWidget(self.runInformationLabel)
        self.runInfoTableWidget = QtGui.QTableWidget(self.widget_4)
        self.runInfoTableWidget.setObjectName("runInfoTableWidget")
        self.runInfoTableWidget.setColumnCount(0)
        self.runInfoTableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.runInfoTableWidget)
        self.verticalLayout_6.addWidget(self.splitter)
        self.widget_5 = QtGui.QWidget(self.runTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startRunPushButton = QtGui.QPushButton(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startRunPushButton.sizePolicy().hasHeightForWidth())
        self.startRunPushButton.setSizePolicy(sizePolicy)
        self.startRunPushButton.setObjectName("startRunPushButton")
        self.horizontalLayout_4.addWidget(self.startRunPushButton)
        spacerItem = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.loadRunFilePushButton = QtGui.QPushButton(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadRunFilePushButton.sizePolicy().hasHeightForWidth())
        self.loadRunFilePushButton.setSizePolicy(sizePolicy)
        self.loadRunFilePushButton.setObjectName("loadRunFilePushButton")
        self.horizontalLayout_4.addWidget(self.loadRunFilePushButton)
        spacerItem1 = QtGui.QSpacerItem(271, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.autorunCheckBox = QtGui.QCheckBox(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autorunCheckBox.sizePolicy().hasHeightForWidth())
        self.autorunCheckBox.setSizePolicy(sizePolicy)
        self.autorunCheckBox.setObjectName("autorunCheckBox")
        self.horizontalLayout_4.addWidget(self.autorunCheckBox)
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.delayLabel = QtGui.QLabel(self.widget_5)
        self.delayLabel.setObjectName("delayLabel")
        self.horizontalLayout_4.addWidget(self.delayLabel)
        self.autorunDelayLineEdit = QtGui.QLineEdit(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autorunDelayLineEdit.sizePolicy().hasHeightForWidth())
        self.autorunDelayLineEdit.setSizePolicy(sizePolicy)
        self.autorunDelayLineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.autorunDelayLineEdit.setObjectName("autorunDelayLineEdit")
        self.horizontalLayout_4.addWidget(self.autorunDelayLineEdit)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.mainTabWidget.addTab(self.runTab, "")
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName("logTab")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.logTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter_2 = QtGui.QSplitter(self.logTab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_8 = QtGui.QWidget(self.splitter_2)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.logTreeWidget = QtGui.QTreeWidget(self.widget_8)
        self.logTreeWidget.setObjectName("logTreeWidget")
        self.logTreeWidget.headerItem().setText(0, "1")
        self.verticalLayout_8.addWidget(self.logTreeWidget)
        self.widget_9 = QtGui.QWidget(self.splitter_2)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.logInfoLabel = QtGui.QLabel(self.widget_9)
        self.logInfoLabel.setObjectName("logInfoLabel")
        self.verticalLayout_7.addWidget(self.logInfoLabel)
        self.logIngotableWidget = QtGui.QTableWidget(self.widget_9)
        self.logIngotableWidget.setObjectName("logIngotableWidget")
        self.logIngotableWidget.setColumnCount(0)
        self.logIngotableWidget.setRowCount(0)
        self.verticalLayout_7.addWidget(self.logIngotableWidget)
        self.verticalLayout_9.addWidget(self.splitter_2)
        self.widget_10 = QtGui.QWidget(self.logTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.setLogFilePushButton = QtGui.QPushButton(self.widget_10)
        self.setLogFilePushButton.setObjectName("setLogFilePushButton")
        self.horizontalLayout_3.addWidget(self.setLogFilePushButton)
        spacerItem3 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.deleteLogItemPushButton = QtGui.QPushButton(self.widget_10)
        self.deleteLogItemPushButton.setObjectName("deleteLogItemPushButton")
        self.horizontalLayout_3.addWidget(self.deleteLogItemPushButton)
        spacerItem4 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.editLogNotesPushButton = QtGui.QPushButton(self.widget_10)
        self.editLogNotesPushButton.setObjectName("editLogNotesPushButton")
        self.horizontalLayout_3.addWidget(self.editLogNotesPushButton)
        spacerItem5 = QtGui.QSpacerItem(273, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_9.addWidget(self.widget_10)
        self.mainTabWidget.addTab(self.logTab, "")
        self.plotTab = QtGui.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.mainTabWidget.addTab(self.plotTab, "")
        self.positionTab = QtGui.QWidget()
        self.positionTab.setObjectName("positionTab")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.positionTab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem6 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem6)
        self.widget_2 = QtGui.QWidget(self.positionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.widget_11 = QtGui.QWidget(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.positionLabel = QtGui.QLabel(self.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionLabel.sizePolicy().hasHeightForWidth())
        self.positionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(28)
        self.positionLabel.setFont(font)
        self.positionLabel.setObjectName("positionLabel")
        self.verticalLayout.addWidget(self.positionLabel)
        spacerItem8 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.velocityLabel = QtGui.QLabel(self.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel.sizePolicy().hasHeightForWidth())
        self.velocityLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(28)
        self.velocityLabel.setFont(font)
        self.velocityLabel.setObjectName("velocityLabel")
        self.verticalLayout.addWidget(self.velocityLabel)
        self.horizontalLayout_2.addWidget(self.widget_11)
        spacerItem9 = QtGui.QSpacerItem(56, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_10.addWidget(self.widget_2)
        spacerItem10 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem10)
        self.line = QtGui.QFrame(self.positionTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_10.addWidget(self.line)
        self.frame = QtGui.QFrame(self.positionTab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_12 = QtGui.QWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtGui.QLabel(self.widget_12)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.widget_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_2.addWidget(self.widget_12)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_3 = QtGui.QWidget(self.groupBox_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtGui.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_11.addWidget(self.widget_3)
        spacerItem14 = QtGui.QSpacerItem(20, 129, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem14)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.verticalLayout_10.addWidget(self.frame)
        self.mainTabWidget.addTab(self.positionTab, "")
        self.verticalLayout_4.addWidget(self.mainTabWidget)
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_6 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stopPushButton = QtGui.QPushButton(self.widget_6)
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout_5.addWidget(self.stopPushButton)
        spacerItem15 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.enablePushButton = QtGui.QPushButton(self.widget_6)
        self.enablePushButton.setObjectName("enablePushButton")
        self.horizontalLayout_5.addWidget(self.enablePushButton)
        self.horizontalLayout.addWidget(self.widget_6)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.modeLabel = QtGui.QLabel(self.widget)
        self.modeLabel.setObjectName("modeLabel")
        self.horizontalLayout.addWidget(self.modeLabel)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.statusLabel = QtGui.QLabel(self.widget)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout.addWidget(self.statusLabel)
        self.verticalLayout_4.addWidget(self.widget)
        SledControl_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SledControl_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 25))
        self.menubar.setObjectName("menubar")
        SledControl_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SledControl_MainWindow)
        self.statusbar.setObjectName("statusbar")
        SledControl_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SledControl_MainWindow)
        self.mainTabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SledControl_MainWindow)

    def retranslateUi(self, SledControl_MainWindow):
        SledControl_MainWindow.setWindowTitle(QtGui.QApplication.translate("SledControl_MainWindow", "Water Channel - Sled Control", None, QtGui.QApplication.UnicodeUTF8))
        self.runInformationLabel.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.startRunPushButton.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.loadRunFilePushButton.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.autorunCheckBox.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Autorun", None, QtGui.QApplication.UnicodeUTF8))
        self.delayLabel.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Delay (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.runTab), QtGui.QApplication.translate("SledControl_MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.logInfoLabel.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.setLogFilePushButton.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Set Log ", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteLogItemPushButton.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Delete Item", None, QtGui.QApplication.UnicodeUTF8))
        self.editLogNotesPushButton.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Edit Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.logTab), QtGui.QApplication.translate("SledControl_MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.plotTab), QtGui.QApplication.translate("SledControl_MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.positionLabel.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Position: 14.234 (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.velocityLabel.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Velocity: 1.234 (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SledControl_MainWindow", "Joy Stick Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Max Velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SledControl_MainWindow", "Feedbac Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.positionTab), QtGui.QApplication.translate("SledControl_MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.stopPushButton.setText(QtGui.QApplication.translate("SledControl_MainWindow", "  Stop ", None, QtGui.QApplication.UnicodeUTF8))
        self.enablePushButton.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.modeLabel.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Mode: Captive Trajectory", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("SledControl_MainWindow", "Status: Halted", None, QtGui.QApplication.UnicodeUTF8))

