/* Auto-generated by genmsg_cpp for file /home/dabiri/ros/distance_118x/msg/DistMsg.msg */
#ifndef DISTANCE_118X_MESSAGE_DISTMSG_H
#define DISTANCE_118X_MESSAGE_DISTMSG_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace distance_118x
{
template <class ContainerAllocator>
struct DistMsg_ : public ros::Message
{
  typedef DistMsg_<ContainerAllocator> Type;

  DistMsg_()
  : header()
  , distance(0.0)
  {
  }

  DistMsg_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , distance(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _distance_type;
  float distance;


private:
  static const char* __s_getDataType_() { return "distance_118x/DistMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4c739b0ad83c2914df6d41fe1b87d25f"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float32 distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(distance);
    return size;
  }

  typedef boost::shared_ptr< ::distance_118x::DistMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::distance_118x::DistMsg_<ContainerAllocator>  const> ConstPtr;
}; // struct DistMsg
typedef  ::distance_118x::DistMsg_<std::allocator<void> > DistMsg;

typedef boost::shared_ptr< ::distance_118x::DistMsg> DistMsgPtr;
typedef boost::shared_ptr< ::distance_118x::DistMsg const> DistMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::distance_118x::DistMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::distance_118x::DistMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace distance_118x

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::distance_118x::DistMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4c739b0ad83c2914df6d41fe1b87d25f";
  }

  static const char* value(const  ::distance_118x::DistMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4c739b0ad83c2914ULL;
  static const uint64_t static_value2 = 0xdf6d41fe1b87d25fULL;
};

template<class ContainerAllocator>
struct DataType< ::distance_118x::DistMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "distance_118x/DistMsg";
  }

  static const char* value(const  ::distance_118x::DistMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::distance_118x::DistMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::distance_118x::DistMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::distance_118x::DistMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::distance_118x::DistMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::distance_118x::DistMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.distance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DistMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::distance_118x::DistMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::distance_118x::DistMsg_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DISTANCE_118X_MESSAGE_DISTMSG_H

