(cl:defpackage setpt_source-msg
  (:use )
  (:export
   "<SETPTACTIONGOAL>"
   "SETPTACTIONGOAL"
   "<SETPTACTIONRESULT>"
   "SETPTACTIONRESULT"
   "<SETPTMSG>"
   "SETPTMSG"
   "<SETPTACTIONFEEDBACK>"
   "SETPTACTIONFEEDBACK"
   "<SETPTGOAL>"
   "SETPTGOAL"
   "<SETPTACTION>"
   "SETPTACTION"
   "<SETPTFEEDBACK>"
   "SETPTFEEDBACK"
   "<SETPTRESULT>"
   "SETPTRESULT"
  ))

