; Auto-generated. Do not edit!


(cl:in-package setpt_source-msg)


;//! \htmlinclude SetptGoal.msg.html

(cl:defclass <SetptGoal> (roslisp-msg-protocol:ros-message)
  ((position
    :reader position
    :initarg :position
    :type cl:float
    :initform 0.0))
)

(cl:defclass SetptGoal (<SetptGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetptGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetptGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name setpt_source-msg:<SetptGoal> is deprecated: use setpt_source-msg:SetptGoal instead.")))

(cl:ensure-generic-function 'position-val :lambda-list '(m))
(cl:defmethod position-val ((m <SetptGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader setpt_source-msg:position-val is deprecated.  Use setpt_source-msg:position instead.")
  (position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetptGoal>) ostream)
  "Serializes a message object of type '<SetptGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'position))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetptGoal>) istream)
  "Deserializes a message object of type '<SetptGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'position) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetptGoal>)))
  "Returns string type for a message object of type '<SetptGoal>"
  "setpt_source/SetptGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetptGoal)))
  "Returns string type for a message object of type 'SetptGoal"
  "setpt_source/SetptGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetptGoal>)))
  "Returns md5sum for a message object of type '<SetptGoal>"
  "e4e11b3af29ed247b2bd150d3f4540f9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetptGoal)))
  "Returns md5sum for a message object of type 'SetptGoal"
  "e4e11b3af29ed247b2bd150d3f4540f9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetptGoal>)))
  "Returns full string definition for message of type '<SetptGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32 position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetptGoal)))
  "Returns full string definition for message of type 'SetptGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32 position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetptGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetptGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SetptGoal
    (cl:cons ':position (position msg))
))
